name: Build Nightly Wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # There's a bug in which if PyNDS is built with gcc on release mode
      # we get an undefined symbol error, so we build with clang for now
      - name: Install Clang
        if: runner.os == 'Linux'
        run: sudo apt install clang

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build Wheel
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            export CC=clang
            export CXX=clang++
          fi
          python setup.py bdist_wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ runner.os }}
          path: dist/*.whl
