name: CI Wheels
on: [release, workflow_dispatch]

jobs:
  build-wheels:
    name: "${{ matrix.runs-on }} • ${{ matrix.arch }}"
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            arch: aarch64
          - runs-on: windows-latest
            arch: AMD64
          - runs-on: macos-15
            arch: arm64
          - runs-on: macos-13
            arch: x86_64
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
      with:
            submodules: 'recursive'

    - name: Build wheels
      uses: pypa/cibuildwheel@352e01339f0a173aa2a3eb57f01492e341e83865  # v3.1.3
      env:
        CIBW_ARCHS: "${{ matrix.arch }}"
        CIBW_SKIP: "cp314*"
        CIBW_ENVIRONMENT_MACOS: 'MACOSX_DEPLOYMENT_TARGET=11.0'

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.runs-on }}-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
